version: '2'
services:
  database:
    restart: always
    image: postgres:9.6.2-alpine
    ports:
      - '5433:5432'
    expose:
      - '5432'
  web:
    build: .
    command: >
      sh -c "DATABASE_URL=postgres://postgres:postgres@database:5432/postgres npm run migrate:up &&
             npm run dev"
    volumes:
      - .:/usr/app/
      - /usr/app/app_modules
    ports:
      - '4000:4000'
    depends_on:
      - database
    environment: 
      - DATABASE_URL=postgres://postgres:postgres@database:5432/postgres
      - secretkey=secretkey