version: '2'
services: 
  web:
    build: .
    command: npm run dev
    volumes: 
      - .:/usr/app/
      - /usr/app/app_modules
    ports: 
      - "3000:3000"
    depends_on: 
      - postgres
    environment: 
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/acronyms
  postgres:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: acronyms